ruby-on-rails-files/config/routes.rb
Rails.application.routes.draw do
    resources :chore_lists do
        resources :chore_items 
    end
    
    # What the main link rerouts to
    root "chore_lists#index"
end

ruby-on-rails-files/app/models/chore_item.rb
class ChoreItem < ActiveRecord::Base
  belongs_to :chore_list
end

ruby-on-rails-files/app/models/chore_list.rb
class ChoreList < ActiveRecord::Base
    has_many :chore_items
end

ruby-on-rails-files/app/models/kid.rb
class Kid < ActiveRecord::Base
    
end

ruby-on-rails-files/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby-on-rails-files/app/controllers/chore_items_controller.rb
class ChoreItemsController < ApplicationController
    before_action :set_chore_list
    
    def create
        @chore_item = @chore_list.chore_items.create(chore_item_params)
        redirect_to @chore_list
    end
    
    private
    
    def set_chore_list
        @chore_list = ChoreList.find(params[:chore_list_id])
    end
    
    def chore_item_params
        params[:chore_item].permit(:content)
    end
end

ruby-on-rails-files/app/controllers/chore_lists_controller.rb
class ChoreListsController < ApplicationController
  before_action :set_chore_list, only: [:show, :edit, :update, :destroy]

  # GET /chore_lists
  # GET /chore_lists.json
  def index
    @chore_lists = ChoreList.all
  end

  # GET /chore_lists/1
  # GET /chore_lists/1.json
  def show
  end

  # GET /chore_lists/new
  def new
    @chore_list = ChoreList.new
  end

  # GET /chore_lists/1/edit
  def edit
  end

  # POST /chore_lists
  # POST /chore_lists.json
  def create
    @chore_list = ChoreList.new(chore_list_params)

    respond_to do |format|
      if @chore_list.save
        format.html { redirect_to @chore_list, notice: 'Chore list was successfully created.' }
        format.json { render :show, status: :created, location: @chore_list }
      else
        format.html { render :new }
        format.json { render json: @chore_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chore_lists/1
  # PATCH/PUT /chore_lists/1.json
  def update
    respond_to do |format|
      if @chore_list.update(chore_list_params)
        format.html { redirect_to @chore_list, notice: 'Chore list was successfully updated.' }
        format.json { render :show, status: :ok, location: @chore_list }
      else
        format.html { render :edit }
        format.json { render json: @chore_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chore_lists/1
  # DELETE /chore_lists/1.json
  def destroy
    @chore_list.destroy
    respond_to do |format|
      format.html { redirect_to chore_lists_url, notice: 'Chore list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore_list
      @chore_list = ChoreList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chore_list_params
      params.require(:chore_list).permit(:title)
    end
end

ruby-on-rails-files/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby-on-rails-files/app/helpers/chore_items_helper.rb
module ChoreItemsHelper
end

ruby-on-rails-files/app/helpers/chore_lists_helper.rb
module ChoreListsHelper
end

ruby-on-rails-files/app/views/chore_items/_chore_item.html.erb
<p><%= chore_item.content %></p>

ruby-on-rails-files/app/views/chore_items/_form.html.erb
<%= form_for([@chore_list, @chore_list.chore_items.build]) do |f| %>
    <%= f.text_field :content, placeholder: "Add Chore" %>
    <%= f.submit "Add" %>
<% end %>

ruby-on-rails-files/app/views/chore_lists/_form.html.erb
<%= form_for(@chore_list) do |f| %>
  <% if @chore_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore_list.errors.count, "error") %> prohibited this chore_list from being saved:</h2>

      <ul>
      <% @chore_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby-on-rails-files/app/views/chore_lists/edit.html.erb
<h1>Editing Chore List</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore_list %> |
<%= link_to 'Back', chore_lists_path %>

ruby-on-rails-files/app/views/chore_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chore Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chore_lists.each do |chore_list| %>
      <tr>
        <td><%= chore_list.title %></td>
        <td><%= link_to 'Show', chore_list %></td>
        <td><%= link_to 'Edit', edit_chore_list_path(chore_list) %></td>
        <td><%= link_to 'Destroy', chore_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chore list', new_chore_list_path %>

ruby-on-rails-files/app/views/chore_lists/new.html.erb
<h1>New Chore List</h1>

<%= render 'form' %>

<%= link_to 'Back', chore_lists_path %>

ruby-on-rails-files/app/views/chore_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chore_list.title %>
</p>

<div id="chore_items_wrapper">
    <%= render @chore_list.chore_items %>
<div id="form">
    <%= render "chore_items/form" %>
    </div>
</div>

<%= link_to 'Edit', edit_chore_list_path(@chore_list) %> |
<%= link_to 'Back', chore_lists_path %>

ruby-on-rails-files/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChoreApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>